import 'package:powersync/powersync.dart';

/// PowerSync local-DB schema. PowerSync auto-adds the text `id` column, so only
/// the other columns are declared. Mirrors supabase/migrations/0001_init.sql.
final powerSyncSchema = Schema([
  Table('accounts', [
    Column.text('name'),
    Column.text('type'),
    Column.text('currency'),
    Column.integer('opening_balance'),
    Column.text('color'),
    Column.text('icon'),
    Column.integer('archived'),
    Column.text('group_id'),
    Column.text('user_id'),
  ]),
  Table('account_groups', [
    Column.text('name'),
    Column.integer('sort_order'),
    Column.text('user_id'),
  ]),
  Table('categories', [
    Column.text('parent_id'),
    Column.text('name'),
    Column.text('type'),
    Column.text('color'),
    Column.text('icon'),
    Column.text('user_id'),
  ]),
  Table('transactions', [
    Column.text('account_id'),
    Column.text('category_id'),
    Column.text('type'),
    Column.integer('amount_minor'),
    Column.text('currency'),
    Column.real('exchange_rate'),
    Column.integer('ref_amount_minor'),
    Column.integer('acct_minor'),
    Column.text('payee'),
    Column.text('note'),
    Column.text('date'),
    Column.integer('hijri_year'),
    Column.integer('hijri_month'),
    Column.integer('hijri_day'),
    Column.text('payment_type'),
    Column.text('record_state'),
    Column.text('transfer_pair_id'),
    Column.text('transfer_dir'),
    Column.real('transfer_rate'),
    Column.text('tags'),
    Column.text('added_by'),
    Column.text('debt_id'),
    Column.text('debt_role'),
    Column.text('regular_item_id'),
    Column.text('user_id'),
  ]),
  Table('transaction_splits', [
    Column.text('transaction_id'),
    Column.text('account_id'),
    Column.text('category_id'),
    Column.integer('amount_minor'),
    Column.integer('acct_minor'),
  ]),
  Table('budgets', [
    Column.integer('amount_minor'),
    Column.text('currency'),
    Column.text('period'),
    Column.integer('rollover'),
    Column.text('user_id'),
  ]),
  Table('budget_categories', [
    Column.text('budget_id'),
    Column.text('category_id'),
  ]),
  Table('debts', [
    Column.text('type'),
    Column.text('counterparty'),
    Column.integer('principal_minor'),
    Column.text('currency'),
    Column.text('account_id'),
    Column.text('date_taken'),
    Column.text('due_date'),
    Column.text('note'),
    Column.text('status'),
    Column.text('initial_tx_id'),
    Column.text('user_id'),
  ]),
  Table('regular_items', [
    Column.text('name'),
    Column.text('category_id'),
    Column.text('account_id'),
    Column.text('currency'),
    Column.integer('default_amount_minor'),
    Column.text('icon'),
    Column.text('color'),
    Column.text('frequency'),
    Column.text('user_id'),
  ]),
  Table('profiles', [
    Column.text('home_currency'),
    Column.text('default_currency'),
    Column.text('theme'),
    Column.integer('show_hijri'),
    Column.text('calendar_mode'),
    Column.text('date_format'),
    Column.integer('hijri_offset'),
  ]),
  Table('merchant_categories', [
    Column.text('merchant'),
    Column.text('category_id'),
    Column.text('user_id'),
  ]),
  // Global table (no user_id). The sync stream must alias the PK:
  //   SELECT code AS id, code, rate FROM fx_rates
  Table('fx_rates', [
    Column.text('code'),
    Column.real('rate'),
  ]),
]);
