// One-time blob→rows migration: converts a legacy "Settings → Export JSON"
// file into SQL for the normalized Supabase schema.
//
// USAGE (on the Windows machine):
//   dart tools/migrate_legacy_blob.dart path\to\pocket-export.json > migrate.sql
//   then: open migrate.sql, REPLACE __USER_ID__ with the target auth.users id
//   (Supabase → Authentication → copy the user's UUID), and run it in the
//   SQL editor. Re-running is safe: ids are deterministic (UUIDv5 of the
//   legacy id) and every insert is ON CONFLICT DO NOTHING.
//
// DESIGN NOTES
//  * Legacy stored a CURRENT balance per account; the new schema derives
//    balances from opening_balance + ledger. We therefore compute
//    opening_balance = legacy.balance − Σ(signed ledger impacts), using the
//    embedded rate table for cross-currency rows (warnings are printed to
//    stderr when that happens — verify those accounts after import).
//  * Legacy ids ('acc_x1', 'tx_abc') are not uuids; the SQL maps them with
//    uuid_generate_v5(uuid_ns_url(), 'pocket:<legacy-id>') so references
//    (transfer pairs, debts, parents) stay consistent and re-runs collide.
//  * hijri snapshots, tags, recurring json, splits, debts, regular items and
//    the profile row are all carried over.

import 'dart:convert';
import 'dart:io';

const Map<String, double> kRates = {
  'USD': 1.0, 'EUR': 0.9, 'GBP': 0.78, 'INR': 83.0, 'KES': 130.0,
  'AED': 3.67, 'SAR': 3.75, 'PKR': 278.0, 'LKR': 300.0, 'TZS': 2600.0,
  'UGX': 3700.0, 'JPY': 155.0, 'CAD': 1.36, 'AUD': 1.5,
};

void main(List<String> args) {
  if (args.isEmpty) {
    stderr.writeln(
        'Usage: dart tools/migrate_legacy_blob.dart <export.json> [> out.sql]');
    exit(1);
  }
  final raw = File(args.first).readAsStringSync();
  final state = jsonDecode(raw) as Map<String, dynamic>;
  final out = StringBuffer();
  final warnings = <String>[];

  final accounts = _list(state['accounts']);
  final categories = _list(state['categories']);
  final transactions = _list(state['transactions']);
  final budgets = _list(state['budgets']);
  final debts = _list(state['debts']);
  final regularItems = _list(state['regularItems']);
  final user = (state['user'] as Map?)?.cast<String, dynamic>() ?? {};

  out.writeln('-- Generated by tools/migrate_legacy_blob.dart');
  out.writeln('-- 1) Replace __USER_ID__ with the auth.users uuid.');
  out.writeln('-- 2) Run in Supabase SQL editor. Safe to re-run.');
  out.writeln("create extension if not exists \"uuid-ossp\";");
  out.writeln('begin;');

  String uid(Object? legacyId) => legacyId == null || '$legacyId'.isEmpty
      ? 'null'
      : "uuid_generate_v5(uuid_ns_url(), 'pocket:${_esc('$legacyId')}')";

  // ── profile ──────────────────────────────────────────────────────────
  out.writeln('''
insert into profiles (id, home_currency, default_currency, theme, show_hijri,
  calendar_mode, date_format, hijri_offset)
values ('__USER_ID__', ${_str(user['homeCurrency'] ?? 'USD')},
  ${_str(user['defaultCurrency'] ?? user['homeCurrency'] ?? 'USD')},
  ${_str(user['theme'] ?? 'system')}, ${user['showHijri'] == false ? 'false' : 'true'},
  ${_str(user['calendarMode'] ?? 'both')}, ${_str(user['dateFormat'] ?? 'auto')},
  ${_int(user['hijriOffset']) ?? 0})
on conflict (id) do update set
  home_currency = excluded.home_currency,
  default_currency = excluded.default_currency,
  theme = excluded.theme, show_hijri = excluded.show_hijri,
  calendar_mode = excluded.calendar_mode, date_format = excluded.date_format,
  hijri_offset = excluded.hijri_offset;''');

  // ── accounts (opening_balance = stored balance − ledger impacts) ─────
  final impacts = <String, double>{}; // legacy account id → minor impact
  void addImpact(String accId, String accCcy, num minor, String txCcy,
      String txId) {
    var value = minor.toDouble();
    if (txCcy != accCcy) {
      final from = kRates[txCcy], to = kRates[accCcy];
      if (from == null || to == null) {
        warnings.add('No rate for $txCcy→$accCcy (tx $txId) — impact skipped');
        return;
      }
      value = value / from * to;
      warnings.add(
          'Cross-currency tx $txId converted at the embedded rate — verify account balance');
    }
    impacts[accId] = (impacts[accId] ?? 0) + value;
  }

  final accById = {for (final a in accounts) '${a['id']}': a};
  for (final t in transactions) {
    final accId = '${t['accountId']}';
    final acc = accById[accId];
    if (acc == null) continue;
    final accCcy = '${acc['currency']}';
    final txCcy = '${t['currency'] ?? accCcy}';
    final amount = _int(t['amount']) ?? 0;
    final type = '${t['type']}';
    final sign = switch (type) {
      'expense' => -1,
      'income' => 1,
      'transfer' => t['transferDir'] == 'in' ? 1 : -1,
      _ => 0,
    };
    if (sign != 0) addImpact(accId, accCcy, sign * amount, txCcy, '${t['id']}');
  }

  for (final a in accounts) {
    final stored = (_int(a['balance']) ?? 0).toDouble();
    final opening = (stored - (impacts['${a['id']}'] ?? 0)).round();
    out.writeln('''
insert into accounts (id, user_id, name, type, currency, opening_balance,
  color, icon, archived)
values (${uid(a['id'])}, '__USER_ID__', ${_str(a['name'])}, ${_str(a['type'] ?? 'bank')},
  ${_str(a['currency'])}, $opening, ${_strOrNull(a['color'])}, ${_strOrNull(a['icon'])},
  ${a['archived'] == true ? 'true' : 'false'})
on conflict (id) do nothing;''');
  }

  // ── categories (parents first) ───────────────────────────────────────
  final cats = [...categories]
    ..sort((a, b) =>
        (a['parentId'] == null ? 0 : 1) - (b['parentId'] == null ? 0 : 1));
  for (final c in cats) {
    out.writeln('''
insert into categories (id, user_id, parent_id, name, type, color, icon)
values (${uid(c['id'])}, '__USER_ID__', ${uid(c['parentId'])}, ${_str(c['name'])},
  ${_str(c['type'] ?? 'expense')}, ${_strOrNull(c['color'])}, ${_strOrNull(c['icon'])})
on conflict (id) do nothing;''');
  }

  // ── transactions + splits ────────────────────────────────────────────
  // Pass 1 without transfer_pair_id (FK), pass 2 patches the pairs.
  for (final t in transactions) {
    final hijri = (t['hijriDate'] as Map?)?.cast<String, dynamic>();
    final tags = _list(t['tags']).map((x) => '$x').toList();
    final recurring = t['recurring'];
    out.writeln('''
insert into transactions (id, user_id, account_id, category_id, type,
  amount_minor, currency, exchange_rate, ref_amount_minor, acct_minor, payee,
  note, date, hijri_year, hijri_month, hijri_day, payment_type, record_state,
  transfer_dir, tags, recurring, recurring_source_id, debt_id, debt_role,
  regular_item_id, added_by)
values (${uid(t['id'])}, '__USER_ID__', ${uid(t['accountId'])}, ${uid(t['categoryId'])},
  ${_str(t['type'] ?? 'expense')}, ${_int(t['amount']) ?? 0}, ${_str(t['currency'])},
  ${_num(t['exchangeRate']) ?? 'null'}, ${_int(t['refAmount']) ?? 'null'},
  ${t['currency'] == accById['${t['accountId']}']?['currency'] ? (_int(t['amount']) ?? 0) : 'null'},
  ${_str(t['payee'] ?? '')}, ${_str(t['note'] ?? '')}, ${_str(t['date'])},
  ${_int(hijri?['year']) ?? 'null'}, ${_int(hijri?['month']) ?? 'null'}, ${_int(hijri?['day']) ?? 'null'},
  ${_str(t['paymentType'] ?? 'card')}, ${_str(t['recordState'] ?? 'cleared')},
  ${_strOrNull(t['transferDir'])},
  ${tags.isEmpty ? "'{}'" : "array[${tags.map(_str).join(',')}]"},
  ${recurring is Map ? "'${_esc(jsonEncode(recurring))}'::jsonb" : 'null'},
  ${uid(t['recurringSourceId'])}, ${uid(t['debtId'])}, ${_strOrNull(t['debtRole'])},
  ${uid(t['regularItemId'])}, ${_strOrNull(t['addedBy'])})
on conflict (id) do nothing;''');

    for (final s in _list(t['splits'])) {
      final sMap = (s as Map).cast<String, dynamic>();
      out.writeln('''
insert into transaction_splits (id, transaction_id, account_id, category_id, amount_minor)
values (uuid_generate_v5(uuid_ns_url(), 'pocket:split:${_esc('${t['id']}')}:${_esc('${sMap['categoryId']}')}:${_int(sMap['amount']) ?? 0}'),
  ${uid(t['id'])}, ${uid(sMap['accountId'] ?? t['accountId'])}, ${uid(sMap['categoryId'])}, ${_int(sMap['amount']) ?? 0})
on conflict (id) do nothing;''');
    }
  }
  for (final t in transactions) {
    if (t['transferPairId'] != null) {
      out.writeln(
          'update transactions set transfer_pair_id = ${uid(t['transferPairId'])} '
          'where id = ${uid(t['id'])};');
    }
  }

  // ── budgets ──────────────────────────────────────────────────────────
  for (final b in budgets) {
    out.writeln('''
insert into budgets (id, user_id, amount_minor, currency, period, rollover)
values (${uid(b['id'])}, '__USER_ID__', ${_int(b['amount']) ?? 0}, ${_str(b['currency'])},
  ${_str(b['period'] == 'hijri' ? 'hijri' : 'gregorian')}, ${b['rollover'] == true ? 'true' : 'false'})
on conflict (id) do nothing;''');
    for (final cid in _list(b['categoryIds'])) {
      out.writeln('''
insert into budget_categories (id, budget_id, category_id)
values (uuid_generate_v5(uuid_ns_url(), 'pocket:bc:${_esc('${b['id']}')}:${_esc('$cid')}'),
  ${uid(b['id'])}, ${uid(cid)})
on conflict (id) do nothing;''');
    }
  }

  // ── debts ────────────────────────────────────────────────────────────
  for (final d in debts) {
    out.writeln('''
insert into debts (id, user_id, type, counterparty, principal_minor, currency,
  account_id, date_taken, due_date, note, status, initial_tx_id)
values (${uid(d['id'])}, '__USER_ID__', ${_str(d['type'] ?? 'borrowed')},
  ${_str(d['counterparty'] ?? '')}, ${_int(d['principal']) ?? 0}, ${_str(d['currency'])},
  ${uid(d['accountId'])}, ${_strOrNull(d['dateTaken'])}, ${_strOrNull(d['dueDate'])},
  ${_str(d['note'] ?? '')}, ${_str(d['status'] ?? 'active')}, ${uid(d['initialTxId'])})
on conflict (id) do nothing;''');
  }

  // ── regular items ────────────────────────────────────────────────────
  for (final r in regularItems) {
    out.writeln('''
insert into regular_items (id, user_id, name, default_amount_minor, currency,
  account_id, category_id, icon, color, frequency)
values (${uid(r['id'])}, '__USER_ID__', ${_str(r['name'])},
  ${_int(r['defaultAmount']) ?? 0}, ${_str(r['currency'] ?? 'USD')},
  ${uid(r['accountId'])}, ${uid(r['categoryId'])}, ${_str(r['icon'] ?? 'coffee')},
  ${_str(r['color'] ?? '#f97316')}, ${_str(r['frequency'] ?? 'monthly')})
on conflict (id) do nothing;''');
  }

  out.writeln('commit;');
  stdout.writeln(out);
  stderr.writeln('--- ${accounts.length} accounts, ${categories.length} '
      'categories, ${transactions.length} transactions, ${budgets.length} '
      'budgets, ${debts.length} debts, ${regularItems.length} regular items');
  for (final w in warnings.toSet()) {
    stderr.writeln('WARNING: $w');
  }
}

List<dynamic> _list(Object? v) => v is List ? v : const [];
int? _int(Object? v) =>
    v == null ? null : (v is num ? v.toInt() : int.tryParse('$v'));
String? _num(Object? v) =>
    v == null ? null : (v is num ? '$v' : double.tryParse('$v')?.toString());
String _esc(String s) => s.replaceAll("'", "''");
String _str(Object? v) => "'${_esc('${v ?? ''}')}'";
String _strOrNull(Object? v) =>
    v == null || '$v'.isEmpty ? 'null' : "'${_esc('$v')}'";
